name: CI (lint & type-check)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy
      - name: Ruff lint
        run: |
          ruff version
          ruff check services shared
      - name: Type check (mypy)
        run: |
          mypy --version
          mypy services || true
